spring:
  application:
    name: feign-service
  cloud:
    config:
      uri: http://config-server:8888
server:
  port: 7004

eureka:
  client:
    serviceUrl:
#      defaultZone: http://eureka-server:8761/eureka/
      defaultZone: http://eureka-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream