server:
  port: 7001
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
#      defaultZone: http://eureka-server:8761/eureka/
spring:
  application:
    name: micro-service-1
  cloud:
    config:
      uri: http://config-server:8888
      retry:
        initial-interval: 240000
        max-attempts: 10
        max-interval: 300000