eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/o12425574/spring-cloud-sample.git
          username: o12425574
          password: o12425574@nwytg.net