server:
  port: 7979
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
spring:
  application:
    name: hystrix
management:
  endpoints:
    web:
      exposure:
        include: "*"

